name             'dotfiles'
maintainer       'Andrei Ostanin'
maintainer_email 'aostanin@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures dotfiles'
supports         'gentoo'
version          '0.1.0'
